.travis.yml
Travis is happy with this configuration:
https://travis-ci.org/catalyst/moodle-tool_mfa/builds/610678799?utm_source=github_status&utm_medium=notification
=> Issue 27: Setup Travis

.idea/mfa.iml, action.php, auth.php, classes/event/user_setup_factor.php, classes/local/admin_setting_managemfa.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/local/form/login_form.php, classes/local/form/preferences_form.php, classes/local/form/setup_factor_form.php, classes/plugininfo/factor.php, factor/email/classes/factor.php, factor/email/lang/en/factor_email.php, factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php, index.php, lang/en/tool_mfa.php, lib.php
**In progress**
Issues #11 #43 #40 #39 #16 #31 
- Rename add factor to setup factor;
- Implement has_setup() factor method;
- Implement total passed weight check;
- Implement factor ordering;
- Add an entry to the config log table when call set_config();
=> Release candidate 20191118

action.php, auth.php, classes/local/form/login_form.php
This PR convers issue https://github.com/catalyst/moodle-tool_mfa/issues/37
=> Fix Cancel button on login and setup forms

action.php, auth.php, user_preferences.php
Issue https://github.com/catalyst/moodle-tool_mfa/issues/30
=> Add crumb trail to factor setup page

auth.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/plugininfo/factor.php, factor/totp/classes/factor.php, lib.php
=> Issue #56: Refactored state checks to class based methods

classes/local/admin_setting_managemfa.php, lang/en/tool_mfa.php, phpunit.xml, settings.php, tests/admin_setting_managemfa_test.php, tests/tool_mfa_testcase.php
=> Summary of good conditions for login

auth.php, classes/manager.php, lang/en/tool_mfa.php, lib.php, settings.php, user_preferences.php
Closes #49. Debug mode table will appear during login on auth.php, and in user_preferences.php.
=> Issue #49: Added debug mode

factor/auth/lang/en/factor_auth.php, factor/email/lang/en/factor_email.php, factor/iprange/lang/en/factor_iprange.php, factor/totp/lang/en/factor_totp.php, lang/en/tool_mfa.php
Issue https://github.com/catalyst/moodle-tool_mfa/issues/51
=> Refactor lang strings

auth.php, classes/local/form/login_form.php, classes/manager.php, lib.php, tests/manager_test.php, tests/plugininfo_factor_test.php
=> Issue #65: Refactor auth flow

classes/plugininfo/factor.php
=> Issue #89: Removed fail states from reoccuring in factor queue

factor/auth/classes/factor.php
=> Issue #87: Refactored auth factor to be safe when no config is set

factor/iprange/classes/factor.php, factor/iprange/lang/en/factor_iprange.php, factor/iprange/settings.php
=> IP range factor

factor/grace/classes/factor.php, lib.php
=> Issue #83: Fixed redirect so a user can only access the auth page

auth.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/manager.php, factor/email/classes/event/unauth_email.php, factor/email/classes/factor.php, factor/email/classes/form/email.php, factor/email/email.php, factor/email/lang/en/factor_email.php, factor/email/renderer.php, factor/email/templates/email.mustache, tests/manager_test.php, user_preferences.php
=> Issue #12: Email factor

factor/admin/classes/factor.php, factor/admin/lang/en/factor_admin.php, factor/admin/settings.php, factor/admin/version.php
=> Issue #18: Added admin factor

classes/manager.php, lang/en/tool_mfa.php, renderer.php
=> Issue #106: New error message page with support links

auth.php, classes/local/form/login_form.php, classes/manager.php, factor/email/lang/en/factor_email.php, lang/en/tool_mfa.php, settings.php
=> Issue #102: Bruteforce timer

action.php, classes/manager.php, classes/plugininfo/factor.php, index.php, lib.php, tests/tool_mfa_testcase.php
=> Issue #64: Lib Refactor

classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/manager.php, db/access.php, factor/email/classes/factor.php, factor/nosetup/classes/factor.php, factor/nosetup/classes/privacy/provider.php, factor/nosetup/lang/en/factor_nosetup.php, factor/nosetup/settings.php, factor/nosetup/version.php, factor/totp/classes/factor.php, lang/en/tool_mfa.php, lib.php, tests/manager_test.php, user_preferences.php
Also allows for MFA to be optional. Closes #105 and #8
=> Issue #105: Partial MFA rollout

action.php, lang/en/tool_mfa.php, user_preferences.php
=> Issue #60: Added notification for successful setup of factors

README.md, classes/local/admin_setting_managemfa.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, factor/admin/lang/en/factor_admin.php, factor/auth/classes/factor.php, factor/auth/lang/en/factor_auth.php, factor/email/classes/factor.php, factor/email/lang/en/factor_email.php, factor/grace/lang/en/factor_grace.php, factor/iprange/lang/en/factor_iprange.php, factor/nosetup/lang/en/factor_nosetup.php, factor/secq/classes/factor.php, factor/secq/lang/en/factor_secq.php, factor/totp/lang/en/factor_totp.php, lang/en/tool_mfa.php
=> Issue #112: Added lang strings and methods for accessing strings

classes/manager.php, lang/en/tool_mfa.php, renderer.php
=> Issue #131: Added get cumulative weight to honor factor order

renderer.php
=> Issue #136: Table no longer outputs if empty

classes/local/admin_setting_managemfa.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, factor/grace/classes/factor.php, factor/nosetup/classes/factor.php, tests/admin_setting_managemfa_test.php
=> Issue #132: Added method for checking combination validity

classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php, renderer.php
=> Issue #137: Added method for custom string for setup

action.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/plugininfo/factor.php, factor/admin/classes/factor.php, factor/auth/classes/factor.php, factor/iprange/classes/factor.php, factor/nosetup/classes/factor.php, factor/totp/classes/factor.php, lang/en/tool_mfa.php, renderer.php, tests/manager_test.php, tests/plugininfo_factor_test.php, user_preferences.php
=> Issue #135: Added notice for revoking factors

classes/local/admin_setting_managemfa.php, classes/manager.php, renderer.php
=> Issue #141: Added border class to divs for tables

.travis.yml, classes/manager.php, lang/en/tool_mfa.php, version.php
Closes #148, can no longer reproduced locally, where issue is caused by sitepolicy checks, when define isn't set. Also closes #155 as Travis needed to be green for this PR
=> Issue #148: Fixed error with redirect loop explosions

classes/manager.php
Fixes issue with URL of current page not being correctly determined when installed in a subdirectory.
=> Issue #148: Updated manager to $FULLME

classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php
=> Issue #161: Check TOTP codes for reuse.

factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php, factor/totp/settings.php, factor/totp/tests/factor_test.php
=> Issue #153: Detect clock skew on user device.

classes/local/factor/object_factor_base.php, classes/manager.php, factor/grace/classes/factor.php
=> Issue #168: Added check for deterministic states

README.md, classes/event/user_deleted_factor.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/plugininfo/factor.php, factor/admin/classes/factor.php, factor/auth/classes/factor.php, factor/email/classes/factor.php, factor/grace/classes/factor.php, factor/grace/classes/task/revoke_expired_factors.php, factor/grace/db/tasks.php, factor/grace/lang/en/factor_grace.php, factor/grace/version.php, factor/iprange/classes/factor.php, factor/nosetup/classes/factor.php, factor/nosetup/classes/task/delete_unusable_factors.php, factor/nosetup/db/tasks.php, factor/nosetup/version.php, factor/secq/classes/factor.php, factor/totp/classes/factor.php, factor_report.php, renderer.php, reset_factor.php, version.php
=> Issue #178: Added cronjobs to clear old factors

.travis.yml, factor/totp/extlib/OTPHP/OTP.php, factor/totp/extlib/OTPHP/OTPInterface.php, factor/totp/extlib/OTPHP/ParameterTrait.php, factor/totp/extlib/OTPHP/TOTP.php
=> Issue #187: Updated Ext lib to be PHP 7.0 compatible

db/install.xml, db/upgrade.php, version.php
=> Issue #200: Add indexes to MFA table

classes/manager.php
=> Issue #205: Fixed wantsurl getting lost in redirect

auth.php, classes/manager.php, factor/admin/version.php, factor/auth/version.php, factor/email/version.php, factor/grace/version.php, factor/iprange/version.php, factor/nosetup/version.php, factor/secq/version.php, factor/totp/version.php, lang/en/tool_mfa.php, renderer.php, version.php
=> Changed error page to allow for state changes in factors

README.md, factor/capability/classes/factor.php, factor/capability/classes/privacy/provider.php, factor/capability/db/access.php, factor/capability/lang/en/factor_capability.php, factor/capability/settings.php, factor/capability/version.php
=> Issue #172: Added user capability factor

README.md, factor/role/classes/factor.php, factor/role/classes/privacy/provider.php, factor/role/lang/en/factor_role.php, factor/role/settings.php, factor/role/version.php
=> Issue #219: Added role factor

factor/auth/classes/factor.php
=> Issue #209: Fixed spacing issue between auth types in summary conditions

classes/manager.php
=> Fix for logo in header not showing up when logging in with MFA

classes/local/form/reset_factor.php, classes/manager.php, lang/en/tool_mfa.php, lib.php, reset_factor.php
=> Issue #258: Added bulk action interface for resetting factors

factor/role/classes/factor.php
=> Issue #261: Fixed issue where special roles not respected

factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php
=> Offer link to app on mobile device for totp #271

factor/auth/db/upgrade.php
=> Issue #272: Tightened upgrade conditions to fix regression on upgrade

factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php, factor/totp/settings.php, factor/totp/version.php
=> Added settings around showing totp link #277

classes/manager.php
=> Issue #280: Added debug output to the auth fail screen

classes/manager.php, reset_factor.php
=> Issue #279: Updated conditions for displaying reset warnings to user

lang/en/tool_mfa.php
=> Add missing lang string for tool_mfa_auth table

README.md, auth.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, factor/loginbanner/classes/factor.php, factor/loginbanner/classes/privacy/provider.php, factor/loginbanner/lang/en/factor_loginbanner.php, factor/loginbanner/settings.php, factor/loginbanner/version.php
=> Added a Policy acceptance factor

factor/sms/classes/local/smsgateway/aws_sns.php
=> Replace all non-alphanumeric characters in the site shortname for sender ID

classes/local/factor/object_factor_base.php, classes/manager.php, factor/capability/lang/en/factor_capability.php
https://github.com/catalyst/moodle-tool_mfa/issues/307
=> Lockcount performance improvements

factor/totp/lang/en/factor_totp.php
This should probably be in a template, but the user_preferences page pulls it via a lang string, so its easier just to throw it straight in there.
=> Add additional TOTP apps

.github/workflows/ci.yml, auth.php, classes/local/factor/object_factor.php, classes/local/factor/object_factor_base.php, classes/local/form/global_form_manager.php, classes/local/form/login_form.php, classes/local/secret_manager.php, factor/token/classes/event/token_created.php, factor/token/classes/factor.php, factor/token/classes/privacy/provider.php, factor/token/lang/en/factor_token.php, factor/token/settings.php, factor/token/tests/factor_test.php, factor/token/version.php, thirdpartylibs.xml
=> Issue #48: Token factor

factor/grace/classes/factor.php, factor/grace/lang/en/factor_grace.php, factor/grace/settings.php, factor/grace/tests/factor_test.php, factor/grace/version.php, version.php
=> Issue #327: Allow grace to define an ignorelist

.github/workflows/ci.yml, version.php
- chore: set supported versions based on readme
- ci: add release params for automatic directory publishing
=> upgrade ci

auth.php, version.php
=> Remove blocks from auth page #352

action.php, factor/totp/classes/factor.php, factor/totp/lang/en/factor_totp.php, factor/totp/tests/factor_test.php
=> fix(totp): a unique factor will only be stored at most once

classes/manager.php
=> Do not redirect on pages without cookies #364

factor/webauthn/classes/factor.php
The added rule won't display a validation message, but it will stop the user from submitting
=> factor_webauthn: Check response_input on setup has data
